# Smart Hadith Tree - Global AI Rules

You are an expert AI assistant working on the "Smart Hadith Tree" full-stack project.
Follow these guidelines strictly when contributing to this repository.

## 1. Project Structure Overview
- **Backend (`src/`)**: .NET 9 Web API using Clean Architecture.
- **Frontend (`frontend/`)**: Next.js (App Router), TypeScript, Tailwind CSS.
- **Tests (`tests/`)**: xUnit test projects for the backend.
- **Scripts (`scripts/`)**: PowerShell/Batch scripts for local setup and running.
- **Docs (`docs/`)**: Architecture diagrams, prompts, and plans.
- **Experiments (`experiments/`)**: AI testing and prototypes.

## 2. Backend Guidelines (.NET 9 / C#)
- Follow **Clean Architecture** principles strictly:
  - `Domain`: Contains core business logic, entities, and interfaces. NO external dependencies.
  - `Application`: Contains use cases, CQRS commands/queries (MediatR), and DTOs. Depends only on `Domain`.
  - `Infrastructure`: Contains EF Core DbContext, external API clients, and file system interactions. Depends on `Application`.
  - `Api`: The presentation layer (Controllers / Minimal APIs). Depends on `Application` and `Infrastructure` (for DI only).
- Use modern C# features (e.g., file-scoped namespaces, global usings, record types for DTOs/Events).
- Prefer **Asynchronous** programming (`async/await`) for all I/O operations.
- Write unit tests using **xUnit** and **Moq** in the `tests/` directory mirroring the `src/` structure.

## 3. Frontend Guidelines (Next.js / React)
- Use **Next.js App Router** (`frontend/src/app`).
- Default to **React Server Components (RSC)**. Use `"use client"` only when necessary for interactivity or hooks (e.g., `useState`, `useEffect`).
- Write strict **TypeScript**. Avoid `any`; define robust interfaces/types.
- Use **Tailwind CSS** for styling.
- Keep the frontend structure clean: extract reusable components to `frontend/src/components`.

## 4. General Workflows
- **Do not modify `frontend/AGENTS.md` or `frontend/CLAUDE.md`**, as they are autogenerated by Next.js.
- Ensure that you use relative paths (e.g., `..\`) or dynamically resolved root paths in scripts so they remain portable.
- When generating Markdown documentation or architecture changes, place them in the `docs/` folder.
- If you run destructive commands (like `Remove-Item` or `rm`), always ask for user confirmation if the target contains source code.

## 5. Communication & Comments
- Add clear XML doc comments to public APIs and complex backend logic.
- Keep responses concise and prioritize specific answers over generic advice.
- When referencing files, provide the exact path relative to the repository root.
