UPDATE Hadiths SET Chapter = N'كتاب بدء الوحي' WHERE BookName = N'صحيح البخاري' AND Chapter = N'كتاب 1';
UPDATE Hadiths SET Chapter = N'كتاب الإيمان' WHERE BookName = N'صحيح البخاري' AND Chapter = N'كتاب 2';
UPDATE Hadiths SET Chapter = N'كتاب العلم' WHERE BookName = N'صحيح البخاري' AND Chapter = N'كتاب 3';
UPDATE Hadiths SET Chapter = N'كتاب الوضوء' WHERE BookName = N'صحيح البخاري' AND Chapter = N'كتاب 4';
UPDATE Hadiths SET Chapter = N'كتاب الغسل' WHERE BookName = N'صحيح البخاري' AND Chapter = N'كتاب 5';
UPDATE Hadiths SET Chapter = N'كتاب الحيض' WHERE BookName = N'صحيح البخاري' AND Chapter = N'كتاب 6';
UPDATE Hadiths SET Chapter = N'كتاب التيمم' WHERE BookName = N'صحيح البخاري' AND Chapter = N'كتاب 7';
UPDATE Hadiths SET Chapter = N'كتاب الصلاة' WHERE BookName = N'صحيح البخاري' AND Chapter = N'كتاب 8';
UPDATE Hadiths SET Chapter = N'كتاب مواقيت الصلاة' WHERE BookName = N'صحيح البخاري' AND Chapter = N'كتاب 9';
UPDATE Hadiths SET Chapter = N'كتاب الأذان' WHERE BookName = N'صحيح البخاري' AND Chapter = N'كتاب 10';
UPDATE Hadiths SET Chapter = N'كتاب الجمعة' WHERE BookName = N'صحيح البخاري' AND Chapter = N'كتاب 11';
UPDATE Hadiths SET Chapter = N'كتاب صلاة الخوف' WHERE BookName = N'صحيح البخاري' AND Chapter = N'كتاب 12';
UPDATE Hadiths SET Chapter = N'كتاب العيدين' WHERE BookName = N'صحيح البخاري' AND Chapter = N'كتاب 13';
UPDATE Hadiths SET Chapter = N'كتاب الوتر' WHERE BookName = N'صحيح البخاري' AND Chapter = N'كتاب 14';
UPDATE Hadiths SET Chapter = N'كتاب الاستسقاء' WHERE BookName = N'صحيح البخاري' AND Chapter = N'كتاب 15';
UPDATE Hadiths SET Chapter = N'كتاب الكسوف' WHERE BookName = N'صحيح البخاري' AND Chapter = N'كتاب 16';
UPDATE Hadiths SET Chapter = N'كتاب سجود القرآن' WHERE BookName = N'صحيح البخاري' AND Chapter = N'كتاب 17';
UPDATE Hadiths SET Chapter = N'كتاب تقصير الصلاة' WHERE BookName = N'صحيح البخاري' AND Chapter = N'كتاب 18';
UPDATE Hadiths SET Chapter = N'كتاب التهجد' WHERE BookName = N'صحيح البخاري' AND Chapter = N'كتاب 19';
UPDATE Hadiths SET Chapter = N'كتاب فضل الصلاة في مسجد مكة والمدينة' WHERE BookName = N'صحيح البخاري' AND Chapter = N'كتاب 20';
UPDATE Hadiths SET Chapter = N'كتاب العمل في الصلاة' WHERE BookName = N'صحيح البخاري' AND Chapter = N'كتاب 21';
UPDATE Hadiths SET Chapter = N'كتاب السهو' WHERE BookName = N'صحيح البخاري' AND Chapter = N'كتاب 22';
UPDATE Hadiths SET Chapter = N'كتاب الجنائز' WHERE BookName = N'صحيح البخاري' AND Chapter = N'كتاب 23';
UPDATE Hadiths SET Chapter = N'كتاب الزكاة' WHERE BookName = N'صحيح البخاري' AND Chapter = N'كتاب 24';
UPDATE Hadiths SET Chapter = N'كتاب الحج' WHERE BookName = N'صحيح البخاري' AND Chapter = N'كتاب 25';
UPDATE Hadiths SET Chapter = N'كتاب العمرة' WHERE BookName = N'صحيح البخاري' AND Chapter = N'كتاب 26';
UPDATE Hadiths SET Chapter = N'كتاب المحصر' WHERE BookName = N'صحيح البخاري' AND Chapter = N'كتاب 27';
UPDATE Hadiths SET Chapter = N'كتاب جزاء الصيد' WHERE BookName = N'صحيح البخاري' AND Chapter = N'كتاب 28';
UPDATE Hadiths SET Chapter = N'كتاب فضائل المدينة' WHERE BookName = N'صحيح البخاري' AND Chapter = N'كتاب 29';
UPDATE Hadiths SET Chapter = N'كتاب الصوم' WHERE BookName = N'صحيح البخاري' AND Chapter = N'كتاب 30';
UPDATE Hadiths SET Chapter = N'كتاب صلاة التراويح' WHERE BookName = N'صحيح البخاري' AND Chapter = N'كتاب 31';
UPDATE Hadiths SET Chapter = N'كتاب فضل ليلة القدر' WHERE BookName = N'صحيح البخاري' AND Chapter = N'كتاب 32';
UPDATE Hadiths SET Chapter = N'كتاب الاعتكاف' WHERE BookName = N'صحيح البخاري' AND Chapter = N'كتاب 33';
UPDATE Hadiths SET Chapter = N'كتاب البيوع' WHERE BookName = N'صحيح البخاري' AND Chapter = N'كتاب 34';
UPDATE Hadiths SET Chapter = N'كتاب السلم' WHERE BookName = N'صحيح البخاري' AND Chapter = N'كتاب 35';
UPDATE Hadiths SET Chapter = N'كتاب الشفعة' WHERE BookName = N'صحيح البخاري' AND Chapter = N'كتاب 36';
UPDATE Hadiths SET Chapter = N'كتاب الإجارة' WHERE BookName = N'صحيح البخاري' AND Chapter = N'كتاب 37';
UPDATE Hadiths SET Chapter = N'كتاب الحوالات' WHERE BookName = N'صحيح البخاري' AND Chapter = N'كتاب 38';
UPDATE Hadiths SET Chapter = N'كتاب الكفالة' WHERE BookName = N'صحيح البخاري' AND Chapter = N'كتاب 39';
UPDATE Hadiths SET Chapter = N'كتاب الوكالة' WHERE BookName = N'صحيح البخاري' AND Chapter = N'كتاب 40';
UPDATE Hadiths SET Chapter = N'كتاب المزارعة' WHERE BookName = N'صحيح البخاري' AND Chapter = N'كتاب 41';
UPDATE Hadiths SET Chapter = N'كتاب المساقاة' WHERE BookName = N'صحيح البخاري' AND Chapter = N'كتاب 42';
UPDATE Hadiths SET Chapter = N'كتاب الاستقراض' WHERE BookName = N'صحيح البخاري' AND Chapter = N'كتاب 43';
UPDATE Hadiths SET Chapter = N'كتاب الخصومات' WHERE BookName = N'صحيح البخاري' AND Chapter = N'كتاب 44';
UPDATE Hadiths SET Chapter = N'كتاب اللقطة' WHERE BookName = N'صحيح البخاري' AND Chapter = N'كتاب 45';
UPDATE Hadiths SET Chapter = N'كتاب المظالم' WHERE BookName = N'صحيح البخاري' AND Chapter = N'كتاب 46';
UPDATE Hadiths SET Chapter = N'كتاب الشركة' WHERE BookName = N'صحيح البخاري' AND Chapter = N'كتاب 47';
UPDATE Hadiths SET Chapter = N'كتاب الرهن' WHERE BookName = N'صحيح البخاري' AND Chapter = N'كتاب 48';
UPDATE Hadiths SET Chapter = N'كتاب العتق' WHERE BookName = N'صحيح البخاري' AND Chapter = N'كتاب 49';
UPDATE Hadiths SET Chapter = N'كتاب المكاتب' WHERE BookName = N'صحيح البخاري' AND Chapter = N'كتاب 50';
UPDATE Hadiths SET Chapter = N'كتاب الهبة' WHERE BookName = N'صحيح البخاري' AND Chapter = N'كتاب 51';
UPDATE Hadiths SET Chapter = N'كتاب الشهادات' WHERE BookName = N'صحيح البخاري' AND Chapter = N'كتاب 52';
UPDATE Hadiths SET Chapter = N'كتاب الصلح' WHERE BookName = N'صحيح البخاري' AND Chapter = N'كتاب 53';
UPDATE Hadiths SET Chapter = N'كتاب الشروط' WHERE BookName = N'صحيح البخاري' AND Chapter = N'كتاب 54';
UPDATE Hadiths SET Chapter = N'كتاب الوصايا' WHERE BookName = N'صحيح البخاري' AND Chapter = N'كتاب 55';
UPDATE Hadiths SET Chapter = N'كتاب الجهاد والسير' WHERE BookName = N'صحيح البخاري' AND Chapter = N'كتاب 56';
UPDATE Hadiths SET Chapter = N'كتاب فرض الخمس' WHERE BookName = N'صحيح البخاري' AND Chapter = N'كتاب 57';
UPDATE Hadiths SET Chapter = N'كتاب الجزية والموادعة' WHERE BookName = N'صحيح البخاري' AND Chapter = N'كتاب 58';
UPDATE Hadiths SET Chapter = N'كتاب بدء الخلق' WHERE BookName = N'صحيح البخاري' AND Chapter = N'كتاب 59';
UPDATE Hadiths SET Chapter = N'كتاب أحاديث الأنبياء' WHERE BookName = N'صحيح البخاري' AND Chapter = N'كتاب 60';
UPDATE Hadiths SET Chapter = N'كتاب المناقب' WHERE BookName = N'صحيح البخاري' AND Chapter = N'كتاب 61';
UPDATE Hadiths SET Chapter = N'كتاب فضائل أصحاب النبي' WHERE BookName = N'صحيح البخاري' AND Chapter = N'كتاب 62';
UPDATE Hadiths SET Chapter = N'كتاب مناقب الأنصار' WHERE BookName = N'صحيح البخاري' AND Chapter = N'كتاب 63';
UPDATE Hadiths SET Chapter = N'كتاب المغازي' WHERE BookName = N'صحيح البخاري' AND Chapter = N'كتاب 64';
UPDATE Hadiths SET Chapter = N'كتاب التفسير' WHERE BookName = N'صحيح البخاري' AND Chapter = N'كتاب 65';
UPDATE Hadiths SET Chapter = N'كتاب فضائل القرآن' WHERE BookName = N'صحيح البخاري' AND Chapter = N'كتاب 66';
UPDATE Hadiths SET Chapter = N'كتاب النكاح' WHERE BookName = N'صحيح البخاري' AND Chapter = N'كتاب 67';
UPDATE Hadiths SET Chapter = N'كتاب الطلاق' WHERE BookName = N'صحيح البخاري' AND Chapter = N'كتاب 68';
UPDATE Hadiths SET Chapter = N'كتاب النفقات' WHERE BookName = N'صحيح البخاري' AND Chapter = N'كتاب 69';
UPDATE Hadiths SET Chapter = N'كتاب الأطعمة' WHERE BookName = N'صحيح البخاري' AND Chapter = N'كتاب 70';
UPDATE Hadiths SET Chapter = N'كتاب العقيقة' WHERE BookName = N'صحيح البخاري' AND Chapter = N'كتاب 71';
UPDATE Hadiths SET Chapter = N'كتاب الذبائح والصيد' WHERE BookName = N'صحيح البخاري' AND Chapter = N'كتاب 72';
UPDATE Hadiths SET Chapter = N'كتاب الأضاحي' WHERE BookName = N'صحيح البخاري' AND Chapter = N'كتاب 73';
UPDATE Hadiths SET Chapter = N'كتاب الأشربة' WHERE BookName = N'صحيح البخاري' AND Chapter = N'كتاب 74';
UPDATE Hadiths SET Chapter = N'كتاب المرضى' WHERE BookName = N'صحيح البخاري' AND Chapter = N'كتاب 75';
UPDATE Hadiths SET Chapter = N'كتاب الطب' WHERE BookName = N'صحيح البخاري' AND Chapter = N'كتاب 76';
UPDATE Hadiths SET Chapter = N'كتاب اللباس' WHERE BookName = N'صحيح البخاري' AND Chapter = N'كتاب 77';
UPDATE Hadiths SET Chapter = N'كتاب الأدب' WHERE BookName = N'صحيح البخاري' AND Chapter = N'كتاب 78';
UPDATE Hadiths SET Chapter = N'كتاب الاستئذان' WHERE BookName = N'صحيح البخاري' AND Chapter = N'كتاب 79';
UPDATE Hadiths SET Chapter = N'كتاب الدعوات' WHERE BookName = N'صحيح البخاري' AND Chapter = N'كتاب 80';
UPDATE Hadiths SET Chapter = N'كتاب الرقاق' WHERE BookName = N'صحيح البخاري' AND Chapter = N'كتاب 81';
UPDATE Hadiths SET Chapter = N'كتاب القدر' WHERE BookName = N'صحيح البخاري' AND Chapter = N'كتاب 82';
UPDATE Hadiths SET Chapter = N'كتاب الأيمان والنذور' WHERE BookName = N'صحيح البخاري' AND Chapter = N'كتاب 83';
UPDATE Hadiths SET Chapter = N'كتاب كفارات الأيمان' WHERE BookName = N'صحيح البخاري' AND Chapter = N'كتاب 84';
UPDATE Hadiths SET Chapter = N'كتاب الفرائض' WHERE BookName = N'صحيح البخاري' AND Chapter = N'كتاب 85';
UPDATE Hadiths SET Chapter = N'كتاب الحدود' WHERE BookName = N'صحيح البخاري' AND Chapter = N'كتاب 86';
UPDATE Hadiths SET Chapter = N'كتاب الديات' WHERE BookName = N'صحيح البخاري' AND Chapter = N'كتاب 87';
UPDATE Hadiths SET Chapter = N'كتاب استتابة المرتدين والمعاندين وقتالهم' WHERE BookName = N'صحيح البخاري' AND Chapter = N'كتاب 88';
UPDATE Hadiths SET Chapter = N'كتاب الإكراه' WHERE BookName = N'صحيح البخاري' AND Chapter = N'كتاب 89';
UPDATE Hadiths SET Chapter = N'كتاب الحيل' WHERE BookName = N'صحيح البخاري' AND Chapter = N'كتاب 90';
UPDATE Hadiths SET Chapter = N'كتاب التعبير' WHERE BookName = N'صحيح البخاري' AND Chapter = N'كتاب 91';
UPDATE Hadiths SET Chapter = N'كتاب الفتن' WHERE BookName = N'صحيح البخاري' AND Chapter = N'كتاب 92';
UPDATE Hadiths SET Chapter = N'كتاب الأحكام' WHERE BookName = N'صحيح البخاري' AND Chapter = N'كتاب 93';
UPDATE Hadiths SET Chapter = N'كتاب التمني' WHERE BookName = N'صحيح البخاري' AND Chapter = N'كتاب 94';
UPDATE Hadiths SET Chapter = N'كتاب أخبار الآحاد' WHERE BookName = N'صحيح البخاري' AND Chapter = N'كتاب 95';
UPDATE Hadiths SET Chapter = N'كتاب الاعتصام بالكتاب والسنة' WHERE BookName = N'صحيح البخاري' AND Chapter = N'كتاب 96';
UPDATE Hadiths SET Chapter = N'كتاب التوحيد' WHERE BookName = N'صحيح البخاري' AND Chapter = N'كتاب 97';
