// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartHadithTree.Infrastructure.Data;

#nullable disable

namespace SmartHadithTree.Infrastructure.Data.Migrations
{
    [DbContext(typeof(HadithTreeDbContext))]
    [Migration("20260906042729_RemoveSequentialIdDefault")]
    partial class RemoveSequentialIdDefault
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("Arabic_100_CI_AI")
                .HasAnnotation("ProductVersion", "9.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SmartHadithTree.Domain.Entities.HadithText", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BookName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .UseCollation("Arabic_100_CI_AI");

                    b.Property<string>("Chapter")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .UseCollation("Arabic_100_CI_AI");

                    b.Property<string>("FullIsnadText")
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Arabic_100_CI_AI");

                    b.Property<int>("HadithNumber")
                        .HasColumnType("int");

                    b.Property<string>("MatnArabic")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Arabic_100_CI_AI");

                    b.Property<string>("Volume")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("HadithNumber")
                        .HasDatabaseName("IX_Hadiths_HadithNumber");

                    b.HasIndex("BookName", "HadithNumber")
                        .HasDatabaseName("IX_Hadiths_BookName_HadithNumber");

                    b.ToTable("Hadiths", (string)null);
                });

            modelBuilder.Entity("SmartHadithTree.Domain.Entities.Narrator", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Biography")
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Arabic_100_CI_AI");

                    b.Property<string>("BirthPlace")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .UseCollation("Arabic_100_CI_AI");

                    b.Property<int?>("BirthYearHijri")
                        .HasColumnType("int");

                    b.Property<string>("DeathPlace")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .UseCollation("Arabic_100_CI_AI");

                    b.Property<int?>("DeathYearHijri")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .UseCollation("Arabic_100_CI_AI");

                    b.Property<string>("GenerationTier")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .UseCollation("Arabic_100_CI_AI");

                    b.Property<string>("KnownAs")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .UseCollation("Arabic_100_CI_AI");

                    b.Property<string>("Kunyah")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .UseCollation("Arabic_100_CI_AI");

                    b.HasKey("Id");

                    b.HasIndex("DeathYearHijri")
                        .HasDatabaseName("IX_Narrators_DeathYearHijri");

                    b.HasIndex("FullName")
                        .HasDatabaseName("IX_Narrators_FullName");

                    b.HasIndex("KnownAs")
                        .HasDatabaseName("IX_Narrators_KnownAs");

                    b.ToTable("Narrators", (string)null);
                });

            modelBuilder.Entity("SmartHadithTree.Domain.Entities.ScholarEvaluation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EvaluationText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .UseCollation("Arabic_100_CI_AI");

                    b.Property<Guid>("NarratorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ScholarName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .UseCollation("Arabic_100_CI_AI");

                    b.Property<string>("SourceBook")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .UseCollation("Arabic_100_CI_AI");

                    b.Property<string>("VerdictRating")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .UseCollation("Arabic_100_CI_AI");

                    b.HasKey("Id");

                    b.HasIndex("NarratorId")
                        .HasDatabaseName("IX_ScholarEvaluations_NarratorId");

                    b.HasIndex("ScholarName")
                        .HasDatabaseName("IX_ScholarEvaluations_ScholarName");

                    b.ToTable("ScholarEvaluations", (string)null);
                });

            modelBuilder.Entity("SmartHadithTree.Domain.Entities.Transmission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("HadithId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SheikhId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("StepOrder")
                        .HasColumnType("int");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TransmissionTerm")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .UseCollation("Arabic_100_CI_AI");

                    b.HasKey("Id");

                    b.HasIndex("HadithId", "StepOrder")
                        .IsUnique()
                        .HasDatabaseName("IX_Transmissions_HadithId_StepOrder");

                    b.HasIndex("SheikhId", "StudentId")
                        .HasDatabaseName("IX_Transmissions_SheikhId_StudentId");

                    b.HasIndex("StudentId", "SheikhId")
                        .HasDatabaseName("IX_Transmissions_StudentId_SheikhId");

                    b.ToTable("Transmissions", (string)null);
                });

            modelBuilder.Entity("SmartHadithTree.Domain.Entities.ScholarEvaluation", b =>
                {
                    b.HasOne("SmartHadithTree.Domain.Entities.Narrator", "Narrator")
                        .WithMany("ScholarEvaluations")
                        .HasForeignKey("NarratorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Narrator");
                });

            modelBuilder.Entity("SmartHadithTree.Domain.Entities.Transmission", b =>
                {
                    b.HasOne("SmartHadithTree.Domain.Entities.HadithText", "Hadith")
                        .WithMany("Transmissions")
                        .HasForeignKey("HadithId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartHadithTree.Domain.Entities.Narrator", "Sheikh")
                        .WithMany("TransmissionsAsSheikh")
                        .HasForeignKey("SheikhId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartHadithTree.Domain.Entities.Narrator", "Student")
                        .WithMany("TransmissionsAsStudent")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Hadith");

                    b.Navigation("Sheikh");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("SmartHadithTree.Domain.Entities.HadithText", b =>
                {
                    b.Navigation("Transmissions");
                });

            modelBuilder.Entity("SmartHadithTree.Domain.Entities.Narrator", b =>
                {
                    b.Navigation("ScholarEvaluations");

                    b.Navigation("TransmissionsAsSheikh");

                    b.Navigation("TransmissionsAsStudent");
                });
#pragma warning restore 612, 618
        }
    }
}
